version: '2'
services:
    jhipster-registry:
        extends:
            file: registry.yml
            service: jhipster-registry
        volumes:
            - ./central-server-config:/central-config
        environment:
        <%_ if(profile=='dev') {_%>
            - SPRING_PROFILES_ACTIVE=dev,native
        <%_ } else { _%>
            - GIT_URI=https://github.com/jhipster/jhipster-registry/
            - GIT_SEARCH_PATH=central-config
        <%_ } _%>
<%_ for(var i=0; i<appConfigs.length; i++) { _%>

    <%= appConfigs[i].baseName.toLowerCase() %>:
        extends:
            file: <%= appsFolderPaths[i] %>/src/main/docker/app.<%= profile %>.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-<% if(profile=='dev') {%><%= profile %>-<%}%>app
<%_ if(profile=='prod') {_%>
    <%= appConfigs[i].baseName.toLowerCase() %>-<%= appConfigs[i].prodDatabaseType %>:
        extends:
            file: <%= appsFolderPaths[i] %>/src/main/docker/db.prod.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-<%= appConfigs[i].prodDatabaseType %>
<%_ }} _%>
<%_ if (useElk) { _%>

    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console
<%_ } _%>
