version: '2'
services:
    jhipster-registry:
        extends:
            file: registry.yml
            service: jhipster-registry
        volumes:
            - ./central-server-config:/central-config
    <% for(var i=0; i<appConfigs.length; i++) {%>
    <%= appConfigs[i].baseName.toLowerCase() %>:
        extends:
            file: <%= appsFolderPaths[i] %>/src/main/docker/app.<%= profile %>.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-<% if(profile=='dev') {%><%= profile %>-<%}%>app
        external_links:
            - jhipster-registry
    <% if(profile=='prod') {%>
    <%= appConfigs[i].baseName.toLowerCase() %>-mysql:
        extends:
            file: <%= appsFolderPaths[i] %>/src/main/docker/db.prod.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-mysql<% }} %>
    <% if (useElk) {%>
    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console<% } %>
