version: '2'
services:
    jhipster-registry:
        extends:
            file: registry.yml
            service: jhipster-registry
        volumes:
            - ./central-server-config:/central-config
    <% for(var i=0; i<appConfigs.length; i++) {%>
    <%= appConfigs[i].baseName.toLowerCase() %>:
        extends:
            file: <%= appConfigs[i].baseName.toLowerCase() %>/src/main/docker/app.<%= profile %>.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-<% if(profile=='dev') {%><%= profile %>-<%}%>app
        depends_on:
            - jhipster-registry<% } %>
    <% if (useElk) {%>
    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    elk-kibana:
        extends:
            file: elk.yml
            service: elk-kibana<% } %>
