version: '2'
services:
    jhipster-registry:
        extends:
            file: registry.yml
            service: jhipster-registry
        volumes:
            - ./central-server-config:/central-config
<%_ for(var i=0; i<appConfigs.length; i++) { _%>
    <%= appConfigs[i].baseName.toLowerCase() %>:
        extends:
            file: <%= appsFolderPaths[i] %>/src/main/docker/app.<%= profile %>.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-<% if(profile=='dev') {%><%= profile %>-<%}%>app<% if(profile=='prod') {%>
    <%= appConfigs[i].baseName.toLowerCase() %>-mysql:
        extends:
            file: <%= appsFolderPaths[i] %>/src/main/docker/db.prod.yml
            service: <%= appConfigs[i].baseName.toLowerCase() %>-mysql
<%_ }} _%>
<%_ if (useElk) { _%>
    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console
<%_ } _%>
